// GENERATED by `osy control build` from the `control PdfViewer` declaration. Do not edit.
//
// Editing this file by hand does not change what the platform sends your shim — it only makes your
// editor disagree with the runtime. `osy control build` fails when this file differs from what the
// declaration would generate, so a stale copy is caught at build rather than in a browser.

/** The control ABI, contractVersion "1.1". Generated with these declarations rather than
 *  published as a package: a package could drift from the platform that compiles the call site, and
 *  keeping the two in step is exactly what contractVersion exists to guarantee. */
export type ContractVersion = "1.1";

/** The app's design tokens. Present for a `headless`/`hookable` control, absent for an `opaque` one —
 *  a self-contained visual island does not render through the app's theme. */
export interface TokenScope {
  /** `var(--colors-border)` — use directly in a style, so a re-theme and dark mode stay live. */
  cssVar(token: string): string;
  /** The current resolved value — for a decision in JS, not for a style. */
  get(token: string): string;
}

/** A credentialed request to the app's OWN server, for a control whose data does not belong in props.
 *  Props are right when the app can hand the control its data outright (a grid's rows, a chart's series);
 *  they are wrong when the control owns a data surface the app never materialises, and would have to
 *  re-marshal through the render tree on every keystroke. Such a control takes the ADDRESS of its data as
 *  props and reads/writes it here. Deliberately generic: it knows nothing about any control family. */
export interface ControlDataScope {
  request(path: string, init?: { method?: string; body?: unknown }): Promise<ControlDataResponse>;
}

export interface ControlDataResponse {
  readonly ok: boolean;
  readonly status: number;
  json(): Promise<unknown>;
}

/** One templated slot the app authored (a per-row builder, or one per column/lane/field). Render ONCE
 *  per element, then `update`/`destroy` — re-rendering the same element leaks the prior instance. */
export interface SlotHandle {
  render(rowData: unknown, el: HTMLElement): SlotInstance;
}

export interface SlotInstance {
  update(rowData: unknown): void;
  destroy(): void;
}

/** This control's OWN style knobs — the ones it declared in `styles { }`, not the app's theme.
 *  `K` is the union of its declared names, so a typo is a compile error here rather than a CSS custom
 *  property that silently resolves to nothing. Values already carry the app's overrides. */
export interface StyleScope<K extends string> {
  /** `var(--control-…)` — use in a style, so an app override stays live without a re-mount. */
  cssVar(name: K): string;
  /** The resolved value now — for a decision in JS, not for a style. */
  get(name: K): string;
}

/** What your `mount` must return. The platform calls BOTH — a handle missing either one is a control
 *  that works until the moment it doesn't, so the shape is checked at mount. */
export interface ControlHandle<P> {
  update(props: P): void;
  destroy(): void;
}

/** One of your own CHROME slots, filled by the app (`slot FindBar { c => … }`). Render it ONCE per
 *  element, then `destroy` — re-rendering the same element leaks the prior instance.
 *
 *  It takes no datum: the content's datum is YOUR commands, and the platform supplies them. That is
 *  what lets the app own how this chrome looks while you keep the behaviour behind it. */
export interface ChromeSlotHandle {
  render(el: HTMLElement): ChromeSlotInstance;
}

export interface ChromeSlotInstance {
  destroy(): void;
}

/** The props `PdfViewer` receives, as the platform marshals them. */
export interface PdfViewerProps {
  /** `Guid fileAsset` */
  fileAsset: string;
  /** `int page` — OPTIONAL: a default is not sent, so apply it in the shim */
  page?: number;
  /** `string fit` — one of: width, page, actual — OPTIONAL: a default is not sent, so apply it in the shim */
  fit?: string;
  /** `int zoom` — OPTIONAL: a default is not sent, so apply it in the shim */
  zoom?: number;
  /** `string layout` — one of: continuous, single — OPTIONAL: a default is not sent, so apply it in the shim */
  layout?: string;
}

/** What the platform offers a mounted `PdfViewer`. */
export interface PdfViewerHost {
  readonly contractVersion: ContractVersion;

  /** Raise one of your DECLARED events. One overload per event, so a name this control never declared
   *  — or the right name with the wrong number of arguments — will not compile. That is the drift that
   *  shipped once already: an `emit` with two arguments against a one-parameter contract, silent at
   *  every layer. */
  emit(event: "loaded", pageCount: number): void;
  emit(event: "pageChanged", page: number): void;
  emit(event: "failed", reason: string): void;

  /** The app's design tokens — this control is `headless`, so it renders through the app's theme. */
  tokens: TokenScope;

  /** A per-row builder template, when the app authored one at the call site. */
  slot?: SlotHandle;
  /** Per-name templates the app authored (`slot <Name> { … }`), keyed by name. */
  cells?: Readonly<Record<string, SlotHandle>>;

  /** The chrome slots you declared, present only when the app filled them. Render each into an
   *  element you position; the platform supplies its content's datum — your own commands — so the
   *  app can write the chrome while you keep the behaviour behind it. */
  slots?: Readonly<Partial<Record<"Toolbar", ChromeSlotHandle>>>;

  /** A credentialed call to the app's own server, when the host supplies the channel. Optional even for
   *  a `headless`/`hookable` control — check it before use. */
  data?: ControlDataScope;

  /** The same-origin, immutable URL of one of the chunks you declared — the assets you load ON
   *  DEMAND rather than at mount. `import(host.chunkUrl("Math"))` for a module; put it in a
   *  `<link>` for a stylesheet. Content-addressed, so the result is cacheable forever, and the
   *  name union is your declaration, so a typo will not compile. */
  chunkUrl(name: "Core" | "Worker" | "Fonts" | "Wasm"): string;
}

/** The handle `PdfViewer` returns: the usual `update`/`destroy`, plus the commands it DECLARED, and the `probe()` a test reads.
 *  The platform checks these are present when it takes the handle, so something you publish
 *  but never implement fails at mount rather than the first time somebody asks for it. */
export interface PdfViewerHandle extends ControlHandle<PdfViewerProps> {
  commands: {
    /** Move to the next page. No-op on the last. */
    nextPage(): void;
    /** Move to the previous page. No-op on the first. */
    previousPage(): void;
    /** Enlarge by one step. */
    zoomIn(): void;
    /** Reduce by one step. */
    zoomOut(): void;
    /** Return to the declared `fit` at 100%. */
    resetZoom(): void;
  };
  /** What is true INSIDE this control right now — read by `Assert.Probe(...)` in an app's
   *  tests. Called on demand, never cached: answer from your live state, not from a field you
   *  set at mount. Must be cheap and must not change anything (a test that perturbs what it is
   *  measuring proves nothing). */
  probe(): {
    /** The page currently showing. */
    page: number;
    /** How many pages the document has; 0 before it opens. */
    pageCount: number;
    /** The current zoom, as the percentage `zoom` is expressed in. */
    zoom: number;
    /** A page has actually been painted to the canvas. */
    rendered: boolean;
    /** Why the document or page failed, when it did. */
    failure?: string | null;
  };
}

/** Your shim's entry point. Export a `mount` with this signature and the platform will drive it. */
export declare function mount(
  el: HTMLElement,
  props: PdfViewerProps,
  host: PdfViewerHost,
): PdfViewerHandle;
