// GENERATED by `osy control build` — do not edit, and do not delete.
//
// This is what holds `PdfViewer`'s shim to the ABI its `control` block declares. The
// `.d.ts` beside it DESCRIBES that contract; nothing compares the two without the line below,
// because a shim's `mount` has its return type inferred. Without it, publishing a command or a
// probe field and never implementing it type-checks clean and fails at mount in a browser.
//
// If this line is the only error you see, your shim's `mount` no longer satisfies its
// declaration — the message names the member. Fix the shim, or change the `control` block and
// re-run `osy control build`.
import type * as Abi from './pdf.control';
import * as Shim from './pdf';

// Assignability, not identity: a shim may be WIDER than the contract, never narrower.
const _conformance: typeof Abi.mount = Shim.mount;
void _conformance;
